site_name: Request Yo Racks Documentation
pages:
  - Home: index.md
  - Contributor Zone:
    - Austin Design Week 2017: 'contributor-zone/adw-2017.md'
    - Goals & Strategy: contributor-zone/goals-strategy.md
    - Technical Overview: 'contributor-zone/technical-overview.md'
    - Services & costs: 'contributor-zone/services-costs.md'
  - Guides:
    - Setting up a local environment: 'guides/setup-full-environment.md'
    - Keeping your branch up-to-date: 'guides/update-branch.md'
    - Installing Git extras: 'guides/git-extras.md'
    - Installing Hub: 'guides/install-hub.md'
    - Installing Liquidprompt: 'guides/install-liquidprompt.md'
  - About:
    - 'License': 'about/license.md'
theme:
  name: material
  palette:
    primary: green
    accent: lime
  logo:
    icon: directions_bike
  feature:
    tabs: true
  favicon: 'img/favicon.ico'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
